# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ workflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: ls --all
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        repository: zacikpet/hbp
        ref: master
        path: ./hbp
    - name: Remove old build
      run: rm -r hbp/client
    - name: Copy new build
      run: mv build hbp/client
    - run: ls --all
      working-directory: hbp

